"""Smoke test for the OKF layer. No MCP client needed.

⚠ MAINTAINER-ONLY, NOT in run_tests.py.
This test reads/writes the REAL global KB and depends on the maintainer's
`algo-engineer` agent (its persona, a `playbook` concept, etc.). A fresh
clone has an empty KB, so this would fail at `assert agents`. New users
should run `python -m tests.run_tests` instead — it runs the three
self-contained tests (test_search/test_mcp_live/test_cross_project) that
build their own temp KBs.

Run from the repo root (maintainer only):
    python -m tests.test_smoke
"""
from ensoul import okf


def main() -> None:
    agents = okf.list_agents()
    assert agents, "no agents found; expected 'algo-engineer'"
    assert agents[0]["agent_id"] == "algo-engineer", agents
    print(f"[1] list_agents OK -> {[a['agent_id'] for a in agents]}")

    idx = okf.agent_index("algo-engineer")
    assert idx["persona_preview"], "AGENT.md missing"
    assert idx["concepts"], "no concepts in bundle"
    print(f"[2] agent_index OK -> {len(idx['concepts'])} concepts:")
    for c in idx["concepts"]:
        print(f"      - {c['concept_id']}  [{c.get('type')}]  {c.get('title')}")

    hits = okf.search("algo-engineer", "negative sampling recommend")
    assert hits, "search returned nothing for known keywords"
    print(f"[3] search OK -> top hit: {hits[0]['concept_id']} (score {hits[0]['score']})")

    before = okf.read_concept("algo-engineer", "playbook")
    assert before["frontmatter"].get("type") == "Playbook"
    print("[4] read_concept OK -> playbook type =",
          before["frontmatter"]["type"])

    written = okf.write_concept(
        "algo-engineer", "projects/smoke-test",
        type="Project", title="smoke test project",
        description="auto-generated by test_smoke; safe to delete",
        body="# note\nthis is a write test and can be deleted.",
        tags=["test"], extra={"project_status": "testing"})
    assert written["frontmatter"]["type"] == "Project"
    assert written["frontmatter"]["project_status"] == "testing"
    print(f"[5] write_concept OK -> wrote {written['concept_id']}")

    log = okf.append_log("algo-engineer", "Creation", "smoke-test via test_smoke")
    print(f"[6] append_log OK -> {log['date']}")

    p = okf._agent_dir("algo-engineer") / "projects" / "smoke-test.md"
    if p.exists():
        p.unlink()
        print("[7] cleanup OK -> removed smoke-test concept")

    print("\nALL GOOD. OKF layer works.")
    print("Next: register the MCP server (see README.md) and chat-test it.")


if __name__ == "__main__":
    main()
